### ISSUE TITLE
Trying to parse empty time string

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-ops-view#129]
Kubernetes returns an empty time string in some cases (I never saw this before). This leads to query failures:
```
ERROR:kube_ops_view.update:Failed to query cluster aws:123123123123:eu-central-1:kube-1 (https://kube-1.example.org): time data '' does not match format '%Y-%m-%dT%H:%M:%SZ' (try 47, wait 60 seconds)
Traceback (most recent call last):
  File "/kube_ops_view/update.py", line 54, in update_clusters
    data = query_cluster(cluster)
  File "/kube_ops_view/kubernetes.py", line 88, in query_kubernetes_cluster
    termination_time = parse_time(termination_time)
  File "/kube_ops_view/kubernetes.py", line 61, in parse_time
    return datetime.datetime.strptime(s, '%Y-%m-%dT%H:%M:%SZ').replace(tzinfo=datetime.timezone.utc).timestamp()
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'

**Comment by hjacobs** [comment]
This seems to be related to a strange failing pod:

```
zkubectl describe pod kube2iam-rr8k4 -n kube-system
Events:
  FirstSeen	LastSeen	Count	From							SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----							-------------	--------	------			-------
  57m		57m		1	{kubelet ip-172-31-1-2.eu-central-1.compute.internal}			Warning		PodFitsHostPorts	Predicate PodFitsHostPorts failed
