### ISSUE TITLE
AttributeError: module 'kubernetes.client.configuration' has no attribute 'host'

### ISSUE THREAD

**Issue by erwbgy** [hjacobs/kube-ops-view#164]
We're successfully running 0.7.1 but changing the image tag to 0.8 results in CrashLoopBackOff:

`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

`$ kubectl -n kube-ops-view get deployment kube-ops-view -o yaml | grep image:
      - image: hjacobs/kube-ops-view:0.8`

`$ kubectl -n kube-ops-view logs kube-ops-view-5bd97cccf6-w47n6
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/kube_ops_view/__main__.py", line 3, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/kube_ops_view/main.py", line 234, in main
    discoverer = StaticClusterDiscoverer(api_server_urls)
  File "/kube_ops_view/cluster_discovery.py", line 80, in __init__
    generate_cluster_id(config.host),
AttributeError: module 'kubernetes.client.configuration' has no attribute 'host'`

**Comment by chz8494** [comment]
confirmed, same error here.
tried both helm chart(change image to 0.8) and yaml from official github repo, showed same error.

**Comment by jordanwilson230** [comment]
Same

**Comment by hjacobs** [comment]
Thanks for reporting, will fix..

**Comment by erwbgy** [comment]
Confirmed that 0.8.1 fixes the issue.  Thanks for the quick fix.
